### ISSUE TITLE
Add 404 Page

### ISSUE THREAD

**Issue by amanRecreates** [amanRecreates/code-type-webapp#28]
![image](https://user-images.githubusercontent.com/87216333/128659487-5a9b7948-24c8-4c04-a389-4ea799532ddb.png)

we need a 404 page, which has a button to go back to home screen.
Page should look good.

**Comment by atoughman** [comment]
UPDATE : We don't need exact 404 page as shown in above image. Instead I will post a new image of how it should look. Till then I am closing this issue.
